# Generated by Django 3.0.2 on 2020-02-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('stock_symbol', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CashFlowData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filing', models.CharField(max_length=500)),
                ('year_1_earnings', models.IntegerField(null=True)),
                ('year_2_earnings', models.IntegerField(null=True)),
                ('year_3_earnings', models.IntegerField(null=True)),
                ('stock_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cscf.Companies')),
            ],
            options={
                'db_table': 'cash_flow',
            },
        ),
    ]
