# Generated by Django 3.0.2 on 2020-02-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowdata',
            name='is_header',
            field=models.SmallIntegerField(default=False),
            preserve_default=False,
        ),
    ]
