# Generated by Django 3.0.2 on 2020-02-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cscf', '0002_cashflowdata_is_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflowdata',
            old_name='year_1_earnings',
            new_name='first_previous_year',
        ),
        migrations.RenameField(
            model_name='cashflowdata',
            old_name='year_2_earnings',
            new_name='second_previous_year',
        ),
        migrations.RenameField(
            model_name='cashflowdata',
            old_name='year_3_earnings',
            new_name='third_previous_year',
        ),
    ]
